//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvMvc.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMyExperiences
    {
        public int ID { get; set; }
        public string Header { get; set; }
        public string SubHeader { get; set; }
        public string Explanation { get; set; }
        public string Date { get; set; }
    }
}
